### ISSUE TITLE
Album on mouse over menu is hidden when using a custom theme

### ISSUE THREAD

**Issue by DougieNeish** [gmusic-utils/gmusic-theme.js#12]
When mousing over an album with a custom theme applied, the menu does not show. See image below.

![](https://cloud.githubusercontent.com/assets/7462084/13550509/3a259d8a-e317-11e5-8a09-a0519a8f2e2c.png)

**Comment by chrismou** [comment]
Fixed in #26 - awaiting review

**Comment by chrismou** [comment]
Merged
