### ISSUE TITLE
Library drop-down active font color

### ISSUE THREAD

**Issue by dns-mcdaid** [gmusic-utils/gmusic-theme.js#13]
In the library section, there's an "ALL MUSIC" drop-down next to shuffle which allows you to toggle Purchased vs. Uploaded content. When open, the text of the active element will turn orange upon mouse-over, regardless of theme modifications. Moved from [here](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/227)

**Comment by chrismou** [comment]
@MarshallOfSound I've fixed this ticket, but what's going on with this whole `npm run build` thing before I PR?  Whatever you did an hour ago changed it all back to how it was, now I'm running it again and it's picking up another 700+ changes in dist/gmusic-theme.js

**Comment by MarshallOfSound** [comment]
I have no idea, it looks like your mac build of a package is different to mine for some reason and therefore results in a different build.  I don't see how or why.  Have you tried destroying your node_modules folder and reinstalling?

I have and my output didn't change

**Comment by chrismou** [comment]
I've just killed my node_modules, and even running `npm install` regens the files with the 700+ changes when the build kicks in at the end.

Could it be node/npm?

node version: 4.2.4
npm version: 2.14.12

**Comment by MarshallOfSound** [comment]
node version: 4.2.6
npm version: 3.7.1

That major bump in npm might be doing something?

**Comment by MarshallOfSound** [comment]
Fixed in #18
