### ISSUE TITLE
playlist subscribe button not themed right in dark mode

### ISSUE THREAD

**Issue by MightyPork** [gmusic-utils/gmusic-theme.js#14]
![screenshot_2016-03-08_22-10-56](https://cloud.githubusercontent.com/assets/2041118/13616579/c9cc22f0-e57a-11e5-8b74-d1c0523d583d.png)

![screenshot_2016-03-08_22-11-00](https://cloud.githubusercontent.com/assets/2041118/13616581/cc91972c-e57a-11e5-92be-9ff23b2264f6.png)

It appears when you open a playlist created by someone else.

**Comment by MarshallOfSound** [comment]
Might sound silly but can you link me a playlist so I can see this button :+1:

**Comment by MightyPork** [comment]
sure, here's one:
https://play.google.com/music/listen?u=0#/pl/AMaBXynQ_WIeeIQZhTc0HP_N6dqG7GOZCvxJLQISuDpwAgJkhLxkfqfPX-cn-w6NzZu-32ZUyiJJ4llau5kk4cbwzuhmyZtfNg%3D%3D

**Comment by chrismou** [comment]
@MarshallOfSound I've just spent about half hour puzzling out the correct combination of styles to get these buttons looking right on the Radiant dark themes.  Want me to grab this ticket or have you got it in hand?

**Comment by chrismou** [comment]
I've done it anyway, seeing as I'm on a bit of a roll this morning. PR incoming.

**Comment by MarshallOfSound** [comment]
#onaroll :+1:

**Comment by chrismou** [comment]
Thankfully, Radiant was mostly unaffected by this update. The benefits of having a robust theming framework I guess?  :wink: :stuck_out_tongue_closed_eyes: :trollface:

**Comment by MarshallOfSound** [comment]
:+1: If you cry every time :/
