### ISSUE TITLE
Now playing list text doesn't look to be picking up custom colour

### ISSUE THREAD

**Issue by chrismou** [gmusic-utils/gmusic-theme.js#15]
Think we're targetting this on Radiant with `.material .song-row td`

Am trying to fix it myself, but having some real issues getting this set up in a dev environment so I'm unable to test if my change is actually doing anything.  Might give you a shout later @MarshallOfSound for some tips on getting this set up.

![screenshot 2016-03-09 08 34 23](https://cloud.githubusercontent.com/assets/319883/13629560/c1edc3de-e5d1-11e5-9d84-80649a21e022.png)

**Comment by MarshallOfSound** [comment]
This is strange because mine looks perfectly normal....  Perhaps google is A/B testing some users.  Can you try discover the class required

**Comment by chrismou** [comment]
Any tips on getting dev tools running in Electron?  I had a quick go earlier (using https://github.com/sindresorhus/electron-debug), but the Element tab just gave me a browser object element and I couldn't target anything inside

**Comment by MarshallOfSound** [comment]
Yep.  I should add this to a development FAQ somewhere but it is second nature to me :+1: 
1. Comment out the last two lines of this file https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/src/main/features/core/applicationMenu.js
2. Open dev tools with the standard shortcut (Cmd + Alt + I on mac I think)
3. Run this `document.querySelector('webview').openDevTools()`

You should now have dev tools for the webview element open

**Comment by MarshallOfSound** [comment]
For more reference as to that mysterious object you can read the Web View tag information in the Electron docs

https://github.com/atom/electron/blob/master/docs/api/web-view-tag.md

**Comment by chrismou** [comment]
Cool :+1:  Will get back to you shortly - standup at 10am, then I should be free for a bit

**Comment by chrismou** [comment]
HTML block:

```
<div class="song-details-wrapper"><div class="song-title">Snap Out of It</div><div class="song-artist-album"><a class="song-artist" href="" aria-label="Artist: Arctic Monkeys">Arctic Monkeys</a> - <a class="song-album" href="" data-album-artist="Arctic Monkeys" data-matched-id="Bqkvbl36pdqbs5j7aajw3kt3s6u" aria-label="Album: AM">AM</a></div></div>
```

_CSS rules:_
This applies to the .song-artist and .song-album a tags

```
a, .simple-dialog a {
    color: #212121;
}
```

This applies to the song-title div

```
.material .song-table.mini [data-col="song-details"] .song-title {
    color: #212121;
}
```

https://play-music.gstatic.com/fe/9ff6a899c33697a889eb1101acc0cc5c/listenstyles.css

**Comment by chrismou** [comment]
Interestingly, I can see your `.gmusic-theme .song-row td > *` rule ( `color: #FFFFFF !important;` ) on `.song-artist` but its being override by `a, .simple-dialog a { color: #212121; }`

That's a weird override.  An inline `<style>` tag with an !important being overridden by a stylesheet style applied to a html tag?  What?

**Comment by MarshallOfSound** [comment]
Hmmmm, that makes 0 sense.  Are we sure that it is that style overriding?

**Comment by chrismou** [comment]
According to dev tools, it seems so.  But yeah, this makes zero sense. This isn't how css specificity works, afaik.

**Song title**
![screenshot 2016-03-09 10 23 20](https://cloud.githubusercontent.com/assets/319883/13632313/f95bab88-e5e0-11e5-9e37-541a9dc712c5.png)

**Song Artist**
![screenshot 2016-03-09 10 24 11](https://cloud.githubusercontent.com/assets/319883/13632353/1aa28582-e5e1-11e5-9eeb-a83e2f5cb285.png)

**Comment by chrismou** [comment]
FWIW, if I force `a, .simple-dialog a` into the same style block as `.gmusic-theme .song-row td`, your `!important` does force a color override.

**Comment by MarshallOfSound** [comment]
![wut](https://cloud.githubusercontent.com/assets/6634592/13632562/602cc948-e63e-11e5-9fc5-362288421ed6.PNG)

Interesting I have a class affecting all a tags that you don't appear to ahve

**Comment by chrismou** [comment]
Except, I do...

![screenshot 2016-03-09 10 36 52](https://cloud.githubusercontent.com/assets/319883/13632692/dde4f8c6-e5e2-11e5-9ba0-34dcc18d233b.png)

Had to copy it out into textedit to find it, but it's there

**Comment by MarshallOfSound** [comment]
OK, so where on earth did that class go.  Why isn't it being applied?

**Comment by chrismou** [comment]
OK, so I have this:

![screenshot 2016-03-09 10 38 06](https://cloud.githubusercontent.com/assets/319883/13632724/0b0c4732-e5e3-11e5-88c4-9183e2502176.png)

So shouldn't the declaration be `.gmusic-theme.material` without the space?  Or is `.material` set elsewhere too?

**Comment by MarshallOfSound** [comment]
You can try that, but it works on mine.  Because the element `#nav-content-container` has the class `material` as well.

**Comment by chrismou** [comment]
I'll have a dig around

**Comment by chrismou** [comment]
If ctrl+f on the page and search for nav-content-container, nothing even comes up. Maybe you're right and I'm part of a test group?  Or maybe they're pushing an update and it hasn't propagated across to you?

Seems weird I'm seeing this on 3.0.0 _and_ master.  Initially I thought I might have borked my dev copy.

**Comment by MarshallOfSound** [comment]
It's probably A/B testing, can you just find a class that fixes it and PR it in

**Comment by chrismou** [comment]
Is the minified js created as part of the build process or do I need to sort that?

**Comment by MarshallOfSound** [comment]
You need to do during `npm run build` and stage / commit it

**Comment by chrismou** [comment]
I'm not sure if I'm using a different version of eslint to you, or if I've done something differently, but the diff is insane.  762 additions, 735 deletions?  I only changed 4-5 elements.

Before I PR, have I done something silly?  Initially I ran `npm run lint`, which caused the huge diff.  Have since tried `npm run build` but it didn't make any more changes.

**Comment by chrismou** [comment]
OK, so this is the result of taking out 8 characters (on one line) and running `npm run build`

https://github.com/gmusic-utils/gmusic-theme.js/compare/fix/material-selector-change?expand=1

765 additions and 738 deletions?

**Comment by MarshallOfSound** [comment]
That diff doesn't have any src or lib file changes only dist changes???

**Comment by MarshallOfSound** [comment]
This is what the diff should kinda look like

https://github.com/gmusic-utils/gmusic-theme.js/commit/5bf314c6ebed02b70571c4c21525038ac765a99b

**Comment by chrismou** [comment]
I probably need to spend a bit more time looking into how this library actually works, but I'm not sure there needs to be any changes to style.css, from what I see.  

The entire change was switching `.gmusic-theme .material` to `.gmusic-theme.material` (ie, removing the space) so that it references .material on the body class rather than one further down the stack.  lib/style.css doesn't reference `.gmusic-theme` so there's nothing to change in there.

My concern was more with how much of dist/gmusic-theme.js was changed by running `npm run build`.  I looked at your commit earlier for reference and there was nowhere near that number of changes.  Are we using different version of something?

**Comment by MarshallOfSound** [comment]
Wait, what file / line number did you change.  I think I know what you did :+1:

**Comment by chrismou** [comment]
`dist/gmusic-theme.js`  -- All on line 1591

**Comment by MarshallOfSound** [comment]
Wait, editing the dist is a no go.  You should be editing `src` or `lib` and then the `dist` is built on run of `npm run build`

**Comment by chrismou** [comment]
See, I thought that seemed strange when I was editing it. So I guess the build script is prefixing the .gmusic-theme selector itself based on the rules in styles.css?
Should be back at my laptop in half hour, I'll have a proper look then

**Comment by MarshallOfSound** [comment]
Yup, that magical namespacing is all handled here using `rework`

https://github.com/gmusic-utils/gmusic-theme.js/blob/master/lib/generate-stylesheet.js#L14
