### ISSUE TITLE
playlist author not visible on hover

### ISSUE THREAD

**Issue by MightyPork** [gmusic-utils/gmusic-theme.js#19]
it's a minor bug, not too important; 

![screenshot_2016-03-10_19-10-51](https://cloud.githubusercontent.com/assets/2041118/13679453/18f50cf0-e6f4-11e5-9765-f1a95d1c9cef.png)
![screenshot_2016-03-10_19-11-03](https://cloud.githubusercontent.com/assets/2041118/13679454/18f60664-e6f4-11e5-8812-e9b8f2e02291.png)

**Comment by chrismou** [comment]
I have a fix ready for this, but there's no point pushing until #12 and #14 are merged in, as it'll create a conflict

**Comment by MarshallOfSound** [comment]
@chrismou Is it all good for you to push your fix for this now?

**Comment by chrismou** [comment]
Oh yeah, forgot about this. Will PR in the morning :+1:
