### ISSUE TITLE
Queue is now gray on gray

### ISSUE THREAD

**Issue by MightyPork** [gmusic-utils/gmusic-theme.js#20]
![screenshot_2016-03-10_22-28-38](https://cloud.githubusercontent.com/assets/2041118/13685232/ad284fc0-e70f-11e5-866d-4a11113931cc.png)

**Comment by chrismou** [comment]
https://github.com/gmusic-utils/gmusic-theme.js/pull/16  :+1: 

I'm just glad I'm not the only person seeing it.  We came to the conclusion that I might be in a test group because no-one else had reported it.

**Comment by MightyPork** [comment]
Probably rolling out, been seeing other weirdness too as well over the last day or so.
Vanilla theme it is for now, looking forward to the fix!

**Comment by MarshallOfSound** [comment]
Closing as fixed

**Comment by MarshallOfSound** [comment]
@chrismou The google change just went live, a few things broke so I'm pushing out an urgent fix today.  Might want to do a quick run through of radiant to ensure nothing broke

**Comment by chrismou** [comment]
@MarshallOfSound :+1: Cheers dude, I'll check it out today.  Feeling slightly honoured I was part of the pre release group ;-)

**Comment by MightyPork** [comment]
@MarshallOfSound can I ask how to pull the update to GPMDP?

I'm running from git, did "npm install" and "gulp build", didn't seem to work. I must be missing something.

Edit: nvm I thought npm is clever and works like composer, apparently it doesn't.  `npm update` did the trick. So dumb :(
