### ISSUE TITLE
Song row hover play button and sort arrow wrong colour on dark themes 

### ISSUE THREAD

**Issue by chrismou** [gmusic-utils/gmusic-theme.js#22]
Play button shows as the original dark grey, but should really be white to match the text.  Sort arrow in the header row should also match the # next to it.

![screenshot 2016-03-11 16 40 52](https://cloud.githubusercontent.com/assets/319883/13708739/336f0aae-e7a8-11e5-84a4-f2507ebd8ec0.png)

**Comment by chrismou** [comment]
Looks like this has filtered through to Radiant too, so I'll sort out a fix and port it across to here. Our robust themes have done me no favours this time :laughing:

**Comment by MarshallOfSound** [comment]
"robust" :cactus: 

You aren't going to let that one go aye :+1:

**Comment by chrismou** [comment]
No :wink: :trollface: 

Seriously though, it's just dawned on me that these buttons use a sprite sheet. We have a hacky solution for this in Radiant (trying to puzzle out why it's stopped working) but this might take a bit more thinking here

**Comment by MarshallOfSound** [comment]
I cheated somewhere else and used the awesome css  
`filter: invert()`

Maybe that should be applied here aswell?

**Comment by chrismou** [comment]
Wow, I've not even see the filter rule before. I'll give it a look today.

Odds on it won't work in Safari and IE though. What's our cross browser policy here?  Or am I opening a can of worms by asking?

**Comment by MarshallOfSound** [comment]
http://caniuse.com/#search=filter

My policy is _screw_ IE, Google Play Music doesn't work very well in it so the theming library doesn't need to either :+1: 

I've only ever really tested in Chrome/Chromium but I've used occasionally in firefox with no issue.

Never even tried in safari but I don't see why it wouldn't work :/

**Comment by chrismou** [comment]
So it's not as easy as I thought.  Inverting works for some of the sprites, but the play button becomes this:

<img width="418" alt="screenshot 2016-03-12 14 35 49" src="https://cloud.githubusercontent.com/assets/319883/13727941/9ee840aa-e8fe-11e5-83d4-f3037515038c.png">

So it seems like right now, the options are a) Leave it, b) Replace the graphic, or c) Try to style it to look a bit less out of place. Maybe try to get a light background behind the dark button and border-radius it into a circle or something.

**Comment by chrismou** [comment]
I doubt I'll get to look at this for a week or so, so I'm unassigning for now in case anyone else fancies taking it on in the meantime.  You can see the play button still, so it's not super urgent
