### ISSUE TITLE
Muted colours

### ISSUE THREAD

**Issue by chrismou** [gmusic-utils/gmusic-theme.js#28]
Good example is here:  #19 

The colour scheme is black/white for the main text, then a muted grey colour for the author.

The fix for this is in #27 - the only option in terms of a dynamic colour to use was the white, which fixes the issue but doesn't look great from a design perspective,

Perhaps it'd be worth considering a fore_primary_muted colour?  For white text this could be #aaaaaa and for black maybe #555555

**Comment by MarshallOfSound** [comment]
We can use the existing color library to simply mute the fore_primary color.

I believe an example of this is https://github.com/gmusic-utils/gmusic-theme.js/blob/master/src/gmusic-theme.js#L166

**Comment by MarshallOfSound** [comment]
It's used here

https://github.com/gmusic-utils/gmusic-theme.js/blob/master/src/gmusic-theme.js#L176

**Comment by chrismou** [comment]
Interesting.  Is it worth putting #27 on hold for the minute, try that out, put in a separate PR, then apply it to #27?

**Comment by MarshallOfSound** [comment]
Give it a shot yeah, I believe that color library has a `lighten` method which would be useful here :+1:

**Comment by chrismou** [comment]
Hang on, you've just added support for light themes right?  So this would need to distinguish between the 2.  darken() for dark themes, lighten() for light themes.

Been sat here trying to work out why a 50% lighten() on white text isn't doing anything  :-/

Not exactly my finest moment.

**Comment by chrismou** [comment]
So yeah. How do the light themes work on your electron player?  Does everything get overriden same as the dark themes?  Or is there a smaller selection of selectors that are changed?  

So if I set `.nav-item-container .owner-name to be` to be `color: <<FORE_PRIMARY_MUTED>>`, then apply darken (0.2) to it thats great for dark themes because the white text will go to a muted grey. But will that also apply `FORE_PRIMARY_MUTED` to the light themes?  In effect, it will change it from the muted grey it is now to black?

**Comment by MarshallOfSound** [comment]
Anything in `highlight.css` is only applied on the "light" theme.
Anything in `full.css` is only applied in the "dark" theme.
Anything in common is applied on both

**Comment by chrismou** [comment]
Perfect :+1:
