### ISSUE TITLE
Google just rethemed Google Play Music

### ISSUE THREAD

**Issue by MarshallOfSound** [gmusic-utils/gmusic-theme.js#33]
If you guys head over to GPM in your browser (https://play.google.com/music/listen?u=0#/now) you should see that Google has changed a few things, most notably their standard orange color has changed and their icon/logo has changed.

I'm currently in the progress of doing a test to ensure that the theme still works for everything else but in particular that orange color will need to be updated

/cc @gmusic-utils/gmusic-js

**Comment by twolfson** [comment]
Tangent: I'm going to push a test branch on `gmusic.js` to make sure Travis CI is still green there

**Comment by twolfson** [comment]
Woot, no errors in `gmusic.js` https://travis-ci.org/gmusic-utils/gmusic.js/builds/122689800
