### ISSUE TITLE
Missing Year, Track and Disk When Editing Album

### ISSUE THREAD

**Issue by Alipoodle** [gmusic-utils/gmusic-theme.js#35]
![image](https://cloud.githubusercontent.com/assets/17199186/14492163/6abe3afc-0175-11e6-8b9a-ec0f8bd467ac.png)
As you can see the Year, Tracks and Disk when editing an Album isn't changing colour for dark theme.
Can't find anything else with this problem, ATM.

**Comment by MarshallOfSound** [comment]
Please raise over at the theming library we use https://github.com/gmusic-utils/gmusic-theme.js

**Comment by MarshallOfSound** [comment]
Well dam, now I look like a complete idiot.  That was a default template response, my bad :+1: :cry: :eggplant:

**Comment by Alipoodle** [comment]
Should this be reopened as it's still broken for year.
![image](https://cloud.githubusercontent.com/assets/17199186/15116178/2e4cd558-15fa-11e6-9e32-3e1a75189edf.png)
Edit:
Or Should a new thing be opened?

Noticed that the last release was 9 days ago and may not be in "newest" version.

**Comment by MarshallOfSound** [comment]
Neither, nothing has changed here.  The fix has been implemented but it has not made it's way downstream into GPMDP yet.
