### ISSUE TITLE
Slider knob not fully themed

### ISSUE THREAD

**Issue by KiitoX** [gmusic-utils/gmusic-theme.js#36]
The slider knob seems to be split up into several parts, at least two of them aren't themed...  
The outer ring and that shadow/ripple thing.
![screenshot-2016-04-28-09-33-10](https://cloud.githubusercontent.com/assets/5896952/14878644/1cc4f88e-0d25-11e6-97ee-00d7ad9a8a62.png)

**Comment by MarshallOfSound** [comment]
@MCManuelLP I believe this a new temporary issue due to the theming that Google have applied recently for Prince's death (the purple theme).

I'll look into this one

**Comment by KiitoX** [comment]
Now that the Prince theme has been removed I can confirm that the bug doesn't seem to be temporary.
![screenshot-2016-04-29-08-47-03](https://cloud.githubusercontent.com/assets/5896952/14909735/25313524-0de7-11e6-9408-3a8f060c4357.png)
