### ISSUE TITLE
Dark theme song thumbs up/down not visible on hover

### ISSUE THREAD

**Issue by collinjackson93** [gmusic-utils/gmusic-theme.js#37]
When the queue is open in dark mode, hovering over a song makes the thumbs up/down unfilled. In light mode, when hovering over, both thumbs up/down are visible, but the one that was selected for that track is filled in.

**When not hovering, song (Never Sleep Alone) shows thumbs up.**
![image](https://cloud.githubusercontent.com/assets/5580739/14942504/6020f478-0f84-11e6-9db2-a291bd279579.png)

**When hovering, thumbs up is not visible.**
![image](https://cloud.githubusercontent.com/assets/5580739/14942499/458a4ad8-0f84-11e6-9a3d-8ee6994cbb81.png)

**In light mode, the thumbs up is still visible.**
![image](https://cloud.githubusercontent.com/assets/5580739/14942524/dd2a258e-0f84-11e6-9ebd-b30fae3a7404.png)

**Comment by berryelectronics** [comment]
While we're at it: It seems like the color of the Thumb buttons change when using a custom theme from dark to white-ish

without custom theme
![screenshot 4](https://cloud.githubusercontent.com/assets/12616124/16179332/90dc70b0-3662-11e6-8083-71965ed80db1.png)

with custom theme
![screenshot 5](https://cloud.githubusercontent.com/assets/12616124/16179333/9760026c-3662-11e6-81f5-0bc07bb8e81b.png)

**Comment by berryelectronics** [comment]
Did you fixed the white outline of the buttons?

**Comment by MarshallOfSound** [comment]
@berryelectronics Yup

**Comment by MarshallOfSound** [comment]
> Fix faded colors on rating thumbs in dark and **light** mode 

😆
