### ISSUE TITLE
Pedantic issues

### ISSUE THREAD

**Issue by twolfson** [gmusic-utils/gmusic-theme.js#5]
Since this code is going to live under the `gmusic-utils` organization, I feel like I'm obligated to try to make it the best quality possible. Here are pedantic issues I saw in the repo:
- Remove `Observer` pattern from repo (i.e. `this.events`)
  - There's no need for an observer pattern in this repo; all actions are synchronous and if anyone wants the `Observer` bindings, then they can define that where they use `.enable`/`.disable` in their code
  - https://github.com/MarshallOfSound/gmusic-theme.js/blob/v1.0.1/src/gmusic-theme.js#L9
- Stop using `localStorage` as a global variable
  - https://github.com/MarshallOfSound/gmusic-theme.js/blob/v1.0.1/src/gmusic-theme.js#L11-L13
  - https://github.com/MarshallOfSound/gmusic-theme.js/blob/v1.0.1/src/gmusic-theme.js#L191
  - There's no need to use `localStorage` for marking that we are using a `custom-theme` or not. We can equally use a `this.enabled` or `this.hasCustomTheme` variable from the instance
- Using bespoke CSS functions instead of writing out CSS or CSS precompiler
  - https://github.com/MarshallOfSound/gmusic-theme.js/blob/v1.0.1/src/gmusic-theme.js#L74-L165
  - It's really hard to read CSS like this, especially long lines like https://github.com/MarshallOfSound/gmusic-theme.js/blob/v1.0.1/src/gmusic-theme.js#L105
  - If we step back, we see that we are essentially rolling our own CSS preprocessor. To counteract that, we should consider using one during the `babel` transform process as well. The code would become located in its own file and we could still maintain the mustache-esque variables
    - I think `rework` fits the mold
      - https://www.npmjs.com/package/rework-namespace
      - https://github.com/intesso/rework-prefix-all-selectors
      - https://www.npmjs.com/package/rework-namespace-at
      - https://www.npmjs.com/package/rework-namespace-css
- Relocate `normalSVG` to a standalone file and load it via `brfs` or similar `babel` transform
  - https://github.com/MarshallOfSound/gmusic-theme.js/blob/v1.0.1/src/gmusic-theme.js#L184
  - It's difficult to read the contents of the SVG or see what it looks like. We should consider relocating it to another file for easier viewing.
  - brfs is a browserify transform that converts `fs.readFileSync(filename, 'utf8')` to inlined strings
    - https://github.com/substack/brfs
- Move to catch-all `updateTheme` method that takes an object
  - https://github.com/MarshallOfSound/gmusic-theme.js/blob/v1.0.1/src/gmusic-theme.js#L49
  - https://github.com/MarshallOfSound/gmusic-theme.js/blob/v1.0.1/src/gmusic-theme.js#L54
  - It's super inefficient for us to redraw every time a single color is updated, we should consider aggregating all `update*` methods into an `updateTheme` method that has the signature (`{backPrimary=null, backSecondary=null}`) where we update non-null colors and then redraw at the end
  - As a bonus, if we move to this then our `constructor` can receive the same object to prevent an unnecessary first draw that gets overridden immediately
- Use `classList` instead of `className`
  - https://github.com/MarshallOfSound/gmusic-theme.js/blob/v1.0.1/src/gmusic-theme.js#L29
  - It seems like we are targetting modern browsers (e.g. usage of `DOMParser`), if so then we can use `classList` instead of `className`
    - https://developer.mozilla.org/en-US/docs/Web/API/Element/classList
- Don't query DOM for `#custom-theme-style`
  - https://github.com/MarshallOfSound/gmusic-theme.js/blob/v1.0.1/src/gmusic-theme.js#L19-L22
  - We created the `customThemeStyle` element so we can save it to our instance and directly reference it instead
- Instead of removing the `styleElement`, update its contents
  - We are already wiping out CSS rules with `innerHTML`, maybe we should reuse the `styleElement` instead of deleting/readding it
  - https://github.com/MarshallOfSound/gmusic-theme.js/blob/v1.0.1/src/gmusic-theme.js#L21
- Comments, we are missing so many comments =(

**Comment by MarshallOfSound** [comment]
All these points are beyond valid :+1: 
Lots of what is mentioned is left over hacky code for my specific implementation in GPMDP.  I'll get onto fixing this :)

And

``` js
// Comments are coming :)
```

**Comment by MarshallOfSound** [comment]
## Quick Task List
- [x] Remove observer pattern
- [x] Remove `.localStorage`
- [x] Rework CSS processing
- [x] Extract `SVG` to a separate file
- [x] Move color update methods to a single `updateColors` method
- [x] Move to `classList` instead of `className`
- [x] Keep reference to the style element
- [x] Update `.innerHTML` instead of deleting and readding
- [x] Rework the SVG monitoring technique (Remove the interval)

**Comment by MarshallOfSound** [comment]
@twolfson I've addressed all the things you mentioned and it is looking a lot nicer already :+1: 

Thoughts on the new stuff?

**Comment by MarshallOfSound** [comment]
Also @twolfson I know at the moment I am just committing to master, once this has stabilized over the next few days I'll go through the proper Branch -> PR -> Review process

**Comment by twolfson** [comment]
Heh, yea -- kind of hard to comment on specific lines without a PR format (or commenting on a specific commit)

**Comment by MarshallOfSound** [comment]
It's all in one commit I guess, you could comment on thta.

https://github.com/gmusic-utils/gmusic-theme.js/commit/1317caf40af1820ed553c5f04d2a3e270fa4bf27

But hopefully its all good :100:

**Comment by twolfson** [comment]
You are making a whole lot of progress, things are looking good =)

That being said, I have even more feedback =/
- The `.travis.yml` SVG isn't pointing to `?branch=master`. This could mean that a failing dev branch or pull request could make the build image red. To remedy that, use
  - `[![Build Status](https://travis-ci.org/gmusic-utils/gmusic-theme.js.svg?branch=master)](https://travis-ci.org/gmusic-utils/gmusic-theme.js)`
- Missed some `MarshallOfSound` references
  - https://github.com/gmusic-utils/gmusic-theme.js/search?utf8=%E2%9C%93&q=MarshallOfSound
  - To avoid this, we can use `git grep -i` which searches the git committed files in a project (case insensitive with `-i`)
- SVG and CSS look great
  - If you want to get a little better syntax highlighting, we could use `$FORE_BACKGROUND` and use a syntax like SCSS in our editors
- The final lines of `styles.js` feel like a CSS minifier. Are we trying to minify the code?
  - If so, consider using a minifier like `csso` as it will take care of things like `0px -> 0` and grouping similar rules
    - https://github.com/css/csso/
- While our `inline` function works, it is breaking the mold of a build chain
  - https://github.com/gmusic-utils/gmusic-theme.js/blob/2c103b88c39778152c740676444a9061a164775a/src/gmusic-theme.js#L74-L78
  - Instead, I suggest setting up a build chain via `grunt` or `gulp` that does
    1. Run `rework` functions and compile a `tmp/style.css` file
    2. Run `browserify` with `fs.readFileSync` targetting `tmp/style.css`
  - That being said, this rework code feels a little bit like overkill at second glance so feel free to nuke it altogether
- Instead of having setter/fallback logic at each step, maybe we should reuse `updateColors` in our constructor
  - https://github.com/gmusic-utils/gmusic-theme.js/blob/2c103b88c39778152c740676444a9061a164775a/src/gmusic-theme.js#L14-L18
  - https://github.com/gmusic-utils/gmusic-theme.js/blob/2c103b88c39778152c740676444a9061a164775a/src/gmusic-theme.js#L65-L69

``` js
this.BACK_PRIMARY = '#222'
// ...
document.body.appendChild(this.styleElement);
this.updateColors(options)
```
- I missed this point earlier but in the README, we should actually document all of our colors as `CSS colors`. This means people can use `rgb`, `hsl` or `#` notation
- We added complexity by accepting `enabled` in the constructor. As a result, we missed actions like `body.classList.add('custom')`
  - I suggest using `this.enabled = false; if (options.enable) { this.enable(); }`
  - or always using `this.enabled = false;` and then requiring the user to run `this.enable();`
- There's no need for a `STYLE_STRING` variable, it makes more sense to pass around styles as a value
  - https://github.com/gmusic-utils/gmusic-theme.js/blob/2c103b88c39778152c740676444a9061a164775a/src/gmusic-theme.js#L33-L35
  - Also, side note -- `_defaultStyles` is a misnomer since after customization they are no longer "default"

``` js
var styleString = this._generateStyleString(); // Same as `_defaultStyles()` except doesn't save to `this`
this._flushStyles(styleString);
```

**Comment by twolfson** [comment]
Oh, and one partially unaddressed topic is screenshots for the methods although the methods now should also be updated in the README

**Comment by MarshallOfSound** [comment]
@twolfson I'm just about to push most of those changes but in regards to the "minification" we can't actually minify it because minification processors will throw a massive error at all the "<<AAA>>" variables we have all over the place.  I just killed the new lines to make it go into a string nicer :+1:

**Comment by twolfson** [comment]
Ah, k. For the minifier, I can think of a few options:
- Use CSS variables syntax and keep text replacement (tools like CSSO should be good with this)
  - https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables
- Move color defaults to another file (e.g. `defaults.js`), move to `$variable` syntax for rework and use a `$variable` replacement library
  - `defaults.js: {backPrimary: '#222326', ...}`
  - In `rework` transforms, we would define variables via `require('defaults.js')`
  - In library itself, we would find/replace `defaults.js` variables and replace them with their counterparts
    - i.e. `css.replace(new RegExp(defaults.backPrimary, 'g'), this.backPrimary);`
    - The negative here being a rabbit hole since we need to escape regexp (e.g. what if we use `rgb()` syntax)

**Comment by twolfson** [comment]
More notes:
- This invert filter is probably only good for dark themes (e.g. someone might want to alter hues altogether)
  - https://github.com/gmusic-utils/gmusic-theme.js/blob/927a2ca89ad8663232f525dd59894173850dcb67/lib/style.css#L360-L362
- A few comments in `generate-styles.js` would probably go a long way
  - https://github.com/gmusic-utils/gmusic-theme.js/blob/927a2ca89ad8663232f525dd59894173850dcb67/lib/generate-stylesheet.js
  - For example, "Add a `body.custom` namespace to all of our rules (e.g. `.hello -> body.custom .hello`)", "Make all rules overrides by adding `!important` to each one", "Strip out comments", "Remove noisy newlines"
- README says `new GMusicTheme(window)` which isn't correct =/
  - https://github.com/gmusic-utils/gmusic-theme.js/tree/927a2ca89ad8663232f525dd59894173850dcb67#vanilla
- It's hard to get a good understanding for `config` without seeing an example. Maybe add some functional code to "Getting Started"?

``` js
window.theme = new window.GMusicTheme({
  // Probably use the same colors as the dark skin from Google Music Desktop
  backPrimary: 'green'
});
```
- From my experience, it's nice to document deeper than the first level of options. Here's a suggestion for `config`
  - config `Object` - Container for configuration options
    - backPrimary `String` - [CSS color](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value) to use as background's primary color
      - By default, this is `#222326`
    - backSecondary `String` - [CSS color](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value) to use as background's secondary color
      - By default, this is `#121314`

``` md
- config `Object` - Container for configuration options
    - backPrimary `String` - [CSS color][] to use as background's primary color
        - By default, this is `#222326`
    - backSecondary `String` - [CSS color][] to use as background's secondary color
        - By default, this is `#121314`

[CSS color]: https://developer.mozilla.org/en-US/docs/Web/CSS/color_value
```
- There is a branch whitelist in `.travis.yml`
  - https://github.com/gmusic-utils/gmusic-theme.js/blob/927a2ca89ad8663232f525dd59894173850dcb67/.travis.yml#L6-L13
- There is a comment specific to `gmusic.js` in `.travis.yml`
  - https://github.com/gmusic-utils/gmusic-theme.js/blob/927a2ca89ad8663232f525dd59894173850dcb67/.travis.yml#L16-L17
- We run `_drawLogo` twice when `options.enabled` is `true`
  - Once here: https://github.com/gmusic-utils/gmusic-theme.js/blob/927a2ca89ad8663232f525dd59894173850dcb67/src/gmusic-theme.js#L21
  - Once here: https://github.com/gmusic-utils/gmusic-theme.js/blob/927a2ca89ad8663232f525dd59894173850dcb67/src/gmusic-theme.js#L29
    - Thankfully nothing happens due to `this.enabled` check in `_drawLogo` but we are hitting the DOM =/
- Usually with `brfs`, it's good to locate loading from disk at the top of a file rather than in a function
  - This is to keep coding style consistent with `node` where we would not want to block loading from disk during a running application
  - https://github.com/gmusic-utils/gmusic-theme.js/blob/927a2ca89ad8663232f525dd59894173850dcb67/src/gmusic-theme.js#L76
- I might be missing something but it looks like we never reset the logo upon `disable`
  - https://github.com/gmusic-utils/gmusic-theme.js/blob/927a2ca89ad8663232f525dd59894173850dcb67/src/gmusic-theme.js#L83-L97
  - I would suggest saving the original logo to a variable and then using `replaceChild` to swap back to the default
    - This would also allow for replacing a custom logo more easily
    - https://developer.mozilla.org/en-US/docs/Web/API/Node/replaceChild

Super pedantic:
- It's usually a good idea to keep naming consistent in code and README
  - `config` vs `options`
  - https://github.com/gmusic-utils/gmusic-theme.js/tree/927a2ca89ad8663232f525dd59894173850dcb67#new-gmusicthemeconfig
  - https://github.com/gmusic-utils/gmusic-theme.js/blob/927a2ca89ad8663232f525dd59894173850dcb67/src/gmusic-theme.js#L11
- The `config` and `colorObject` for `updateColors` are identical, we should prob call them both `config`
  - https://github.com/gmusic-utils/gmusic-theme.js/tree/927a2ca89ad8663232f525dd59894173850dcb67#new-gmusicthemeconfig
  - https://github.com/gmusic-utils/gmusic-theme.js/tree/927a2ca89ad8663232f525dd59894173850dcb67#updatecolorscolorobject
  - Also, we can likely say "config\n-Supports all color optons from [updateColors](#updatecolorscolorobject)" for `new GMusicTheme`
    - This will save on space and redundancy
- I would recommend renaming `updateColors` to `updateTheme` as we might want something like `type: light`/`type: dark` due to the invert filter
- We can probably move `'custom'` class to a constant
  - https://github.com/gmusic-utils/gmusic-theme.js/blob/927a2ca89ad8663232f525dd59894173850dcb67/src/gmusic-theme.js#L44
- We should consider something more custom to ourselves than a generic "custom" class, maybe `gmusic-theme-custom`

**Comment by MarshallOfSound** [comment]
I've addressed most of your final comments, all that's left really is some README updates which I'll get round to at some point :+1:

**Comment by twolfson** [comment]
Since you are closing this, I guess you are done with everything for the most part (I still see some pedantic issues) but as mentioned before everything is looking much better :+1:

**Comment by MarshallOfSound** [comment]
Lost internet after closing, a whole bunch of issues are fixed but couldn't
be pushed.  WiFi is shocking....

**Comment by twolfson** [comment]
Alright, here's an aggregate of remaining tasks in case you are still interested:
- This invert filter is probably only good for dark themes (e.g. someone might want to alter hues altogether)
  - https://github.com/gmusic-utils/gmusic-theme.js/blob/927a2ca89ad8663232f525dd59894173850dcb67/lib/style.css#L360-L362
- README says `new GMusicTheme(window)` which isn't correct =/
  - https://github.com/gmusic-utils/gmusic-theme.js/tree/927a2ca89ad8663232f525dd59894173850dcb67#vanilla
- It's hard to get a good understanding for `config` without seeing an example. Maybe add some functional code to "Getting Started"?

``` js
window.theme = new window.GMusicTheme({
  // Probably use the same colors as the dark skin from Google Music Desktop
  backPrimary: 'green'
});
```
- From my experience, it's nice to document deeper than the first level of options. Here's a suggestion for `config`
  - config `Object` - Container for configuration options
    - backPrimary `String` - [CSS color](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value) to use as background's primary color
      - By default, this is `#222326`
    - backSecondary `String` - [CSS color](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value) to use as background's secondary color
      - By default, this is `#121314`

``` md
- config `Object` - Container for configuration options
    - backPrimary `String` - [CSS color][] to use as background's primary color
        - By default, this is `#222326`
    - backSecondary `String` - [CSS color][] to use as background's secondary color
        - By default, this is `#121314`

[CSS color]: https://developer.mozilla.org/en-US/docs/Web/CSS/color_value
```
- There is a comment specific to `gmusic.js` in `.travis.yml`
  - https://github.com/gmusic-utils/gmusic-theme.js/blob/0691b1fcd9fded5828c9a89d35827ed052f57007/.travis.yml#L7-L8
- Save logo elements to instance instead of querying DOM
  - Can use `replaceChild` to swap more easily as well
    - https://developer.mozilla.org/en-US/docs/Web/API/Node/replaceChild
- Inconsistent `config` vs `options` in code vs README
  - https://github.com/gmusic-utils/gmusic-theme.js/tree/927a2ca89ad8663232f525dd59894173850dcb67#new-gmusicthemeconfig
  - https://github.com/gmusic-utils/gmusic-theme.js

**New points:**
- Constants should live in `src` as they are actually used there rather than as an external resource. It's `lib` that is loading them as an external resource
