### ISSUE TITLE
Currently playing song displaying incorrectly with dark theme

### ISSUE THREAD

**Issue by ZephireNZ** [gmusic-utils/gmusic-theme.js#52]
Looks like Google may have changed some web player CSS, as the dark theme breaks on the highlighted song.

![image](https://cloud.githubusercontent.com/assets/1644496/18342120/4a410a60-7601-11e6-9fce-cf1c4ae1a57b.png)

**Comment by Alipoodle** [comment]
Same problem here 
![image](https://cloud.githubusercontent.com/assets/17199186/18350764/51ce9374-75cf-11e6-8656-f8ece9937a70.png)

Recreate:
This isn't a constant thing. No Clue how to recreate.
OS:
Windows 10 (Last update before Anniversary)

**Comment by Alipoodle** [comment]
Found a Fix, Try and Drag Either the currently playing, or another song.
I did the Current song, this only works till another song is played

**Comment by Smashman** [comment]
Fixed in #54
