### ISSUE TITLE
Coloured Top Bar

### ISSUE THREAD

**Issue by Alipoodle** [gmusic-utils/gmusic-theme.js#55]
![image](https://cloud.githubusercontent.com/assets/17199186/18388171/894707e0-7698-11e6-9363-9b191a4765d0.png)
I was wondering if it was possible to be able to make the top bar match your Accent Colour?
If could be added within the desktop settings menu

**Comment by MarshallOfSound** [comment]
> If could be added within the desktop settings menu

This library is more generic than GPMDP think of it as an API

> I was wondering if it was possible to be able to make the top bar match your Accent Colour?

Gonna have to say no to this, our goal is to keep this library super simple and as such we have declined requests like this before.  In the latest release of GPMDP however there is a custom CSS option that would let you implement this option yourself 👍

**Comment by Alipoodle** [comment]
Which is what i was planning on doing
