### ISSUE TITLE
Dark Theme: Play Button in Playlist tab not themed.

### ISSUE THREAD

**Issue by Alipoodle** [gmusic-utils/gmusic-theme.js#56]
http://puu.sh/r6blb/32d0c2031a.png

OS:Win 10 (3.6)

Tags within GPM

.material .sj-play-button-0 #buttonContent.sj-play-button {
    background: <<COLOUR>>;
}

.material .sj-play-button-0 #pulse.sj-play-button {
    background: <<COLOUR>>;
    opacity: .3;
}

This maybe able to simplify but i only know how to use CSS enough to mess with it :D

**Comment by Alipoodle** [comment]
Completed in Pull request #57

**Comment by MarshallOfSound** [comment]
Don't close until the PR is merged 👍
