### ISSUE TITLE
New GPM Update 15/11/2016

### ISSUE THREAD

**Issue by MarshallOfSound** [gmusic-utils/gmusic-theme.js#60]
So I hot fixed a whole bunch of issues with the new UI but I inevitably missed some.  This is just to track them.

* [x] Music Library headings (Playlists, Stations, Etc.) are a bad font color
  * [x] The currently selected heading is also underlined in the wrong color
* [x] On some pages (New Releases) the drop down in the top left is a bad font color
  * [x] The selected drop down option is also the wrong highlight color
* [x] On some pages the playlist open button is a bad font color
* [x] Borders above playlist categories showing in wrong color on playlist menu
* [x] Background parallax header images not visible on dark themes

**Comment by chrismou** [comment]
Need to confirm - I'm not seeing any parallax artist images when visiting an Artist page and scrolling up (Internet where I am is bloody awful though so may not be loading properly)

**Comment by jostrander** [comment]
Still there for me, in browser so no theme:

![image](https://cloud.githubusercontent.com/assets/760989/20269944/45a12932-aa53-11e6-859f-6aa837a71cfe.png)

**Comment by chrismou** [comment]
Dark theme?  And on proper Artist pages?

![screenshot from 2016-11-14 15-15-43](https://cloud.githubusercontent.com/assets/319883/20269993/51714b32-aa7d-11e6-90a1-f71074eacc16.png)

**Comment by chrismou** [comment]
tbf I'm not seeing them on Radio pages either and you clearly can, so this could well just be me

**Comment by jostrander** [comment]
To be fair to you, I wasn't in GPMDP, but on desktop...Checking gpmdp with themes

**Comment by chrismou** [comment]
Yep, definitely just dark themes

![screenshot from 2016-11-14 15-22-16](https://cloud.githubusercontent.com/assets/319883/20270226/2ea615be-aa7e-11e6-8538-c25e4ee95b5c.png)
![screenshot from 2016-11-14 15-22-31](https://cloud.githubusercontent.com/assets/319883/20270227/2ea870d4-aa7e-11e6-8387-d742f2d13420.png)

**Comment by jostrander** [comment]
Must have been something with the latest change because even with the old gmusic-theme dark theme is working on new GPM update.

**Comment by chrismou** [comment]
```
#mainContainer {
   background: <<BACK_PRIMARY>>;
 }
```

On the homepage:

```
.backgroundContainer {
    position: fixed;
    top: 64px;
    right: 0;
    bottom: 0;
    left: 0;
    z-index: -1;
}
```

Artist page:

```
paper-drawer-panel iron-image#material-hero-image {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    padding-top: 50%;
    background-color: #e0e0e0;
    z-index: -1;
```

Frivolous use of z-index, placing the image below the #mainContainer :-/

**Comment by MarshallOfSound** [comment]
Did I do a bad thing 😢  Pr's welcome 😄

**Comment by chrismou** [comment]
Go to bed :joy: 

I'll look into it when I'm home from work, unless someone beats me to it

**Comment by MarshallOfSound** [comment]
I think I've handled all the things 👍 

I did something fancy with the "Home" background.  In the light theme it has fancy images and such which are quite cool and I wanted to keep those.  But some of them are pure white (cry).  So I injected an extra div which overlays on all the backgrounds and makes them like 70% darker 👍 

Try it out and see what it looks like

**Comment by Alipoodle** [comment]
How long till update?
I'm also currently using small sections of the CSS that i was bothered enough to add!

**Comment by MarshallOfSound** [comment]
@Alipoodle I'm going to use master for a few days before pushing it out to everyone.  I'm still finding small things to fix and tweak. 👍

**Comment by Alipoodle** [comment]
OK! 👍

**Comment by chrismou** [comment]
Trying it out today via GPDMP master.  The background overlay seems to work really well.  Good work. :+1:

**Comment by MarshallOfSound** [comment]
@chrismou I've been noticing today that sometimes (randomly) the background overlay disappears.  i think this is linked to me clicking the "Show Latest" button that sometimes appears.  Have you seen this?

**Comment by chrismou** [comment]
@MarshallOfSound On the home screen?  I've not noticed it yet.  tbh I'm not even sure I've seen a Show Latest button pop up. What does that trigger? (don't say it shows the latest :joy:)

**Comment by MarshallOfSound** [comment]
> don't say it shows the latest

I won't say it then 😆 

I think just leaving the player open on the home screen for an extended period of time will trigger it.  It has to be on the home screen though.

**Comment by chrismou** [comment]
Ahhh, I just checked it again and saw the button. No idea what it's showing the latest of :-/

But yeah, I am seeing it. Hit the button, scrolled to the top. and now I've lost the overlay and I'm left with a sort of dark/light theme hybrid. Though clicking into another page, then the home link (via the sidebar menu) seems to fix it.

Will boot up dev tools and see if I can see what's happening next time the button pops up

![screenshot from 2016-11-16 10-09-00](https://cloud.githubusercontent.com/assets/319883/20343055/db33a168-abe4-11e6-9ec3-694feb5b82d1.png)

**Comment by Alipoodle** [comment]
Not sure if this is GPM (site) or GPMDP. But one of the Fixes i did for the theme before seems to have been removed?
Now: http://puu.sh/sk12P/a807e5fccf.png
Before: http://puu.sh/rMnu4/17faf13977.png

**Comment by Alipoodle** [comment]
Towards the Show Latest i believe this is to update the page based upon the music you have just been listening too!

**Comment by MarshallOfSound** [comment]
I think all is good now :+1:
