### ISSUE TITLE
Doesn't always load dark background on Home (Dark Theme)

### ISSUE THREAD

**Issue by Alipoodle** [gmusic-utils/gmusic-theme.js#61]
This image shows when it was broken... _It was not possible to read alot of things on the page_
![image](https://cloud.githubusercontent.com/assets/17199186/21010836/1eeaba14-bd46-11e6-980d-28b5441047cc.png)
Although after changing page and then returning it worked again.
![image](https://cloud.githubusercontent.com/assets/17199186/21010875/637891c4-bd46-11e6-951d-8e448f42330a.png)

I'm see if i can reproduce and find the problem with Dev tools!?

**Comment by MarshallOfSound** [comment]
We are aware of this problem and I know how to reproduce it.  It's very hard to fix and I don't have time at the moment.

Basically sometimes Google refreshs the HTML in the background and it removes my magical dark overlay.

**Comment by MarshallOfSound** [comment]
Idea I stole from a work around I did on another project.  Replace the inserted div with a pseudo `::after` or `::before` element on one of the divs that Google creates.  Then it will always be there 👍

**Comment by pschfr** [comment]
This still happens rarely to me. Perhaps this is as easy to fix with `!important` somewhere? Or somehow checking if the background is light, and making the text dark so it's still readable?
![screenshot from 2017-03-23 22-01-53](https://cloud.githubusercontent.com/assets/490222/24277599/77cafc04-1014-11e7-8ef7-5c6a83b61d52.png)
Running on Ubuntu 16.10, GPMDP 4.0.5.

**Comment by MarshallOfSound** [comment]
@pschfr Your GPMDP version is out of date, please update to `4.2.0`

**Comment by pschfr** [comment]
Ah, thanks! My mistake!
