### ISSUE TITLE
Search box is white for all themes.

### ISSUE THREAD

**Issue by Alipoodle** [gmusic-utils/gmusic-theme.js#64]
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/2129

I don't use the paid version of GPM so I'm unsure if this will work on that as well as i use the Dark theme so this is how it used to be themed.

```
.qp #material-one-middle .material-search, .qp #material-one-middle .material-search:focus {
	background-color: rgba(255,255,255,0.16) !important;
}
```
![image](https://cloud.githubusercontent.com/assets/17199186/22176096/69939f0a-dffa-11e6-9309-b13beb460a0d.png)

**Comment by Alipoodle** [comment]
On Another note, Could someone provide me with CSS to help change the color of the ``Search`` Text unless it will be changed along with the update

**Comment by Alipoodle** [comment]
This could be a ``fix`` but the text might not be able to read.

**Comment by jostrander** [comment]
Seems to be fixed now.
