### ISSUE TITLE
Theme is not applied to Subscribe button in sidebar

### ISSUE THREAD

**Issue by karlding** [gmusic-utils/gmusic-theme.js#66]
**OS:** macOS

**Issue Descriptions:** When using a Google Play Music account that doesn't have a GPM subscription, the Subscribe button in the sidebar does not take on the highlight colours. I'm not sure if this is intentional, but it feels like this should also change colour.

**Steps to Reproduce:**

1. Select a highlight colour
1. Log into an account without a GPM subscription
1. Press the menu icon
1. Notice the Subscribe button does not change colour. Hovering (when using a dark theme) makes the button almost invisible.

![screen shot 2017-03-13 at 4 29 12 pm](https://cloud.githubusercontent.com/assets/6836385/23884836/972a45fe-0845-11e7-8c9d-cd6bccb66724.png)
![screen shot 2017-03-13 at 4 29 27 pm](https://cloud.githubusercontent.com/assets/6836385/23884839/9b388a3e-0845-11e7-9492-8de34fda1b8c.png)

**Comment by MarshallOfSound** [comment]
Can someone without an all access subscription get this one, I have AA 😆

**Comment by karlding** [comment]
I can take a look at this, if it makes things easier. Would you say that the button should be the highlight colour by default, and the hover state uses the same colour as the icons?

**Comment by MarshallOfSound** [comment]
@karlding Try mirror the non-themed behavior but with the themed colors, I don't know what that behavior is but as long as it is close I'll be happy 👍

**Comment by karlding** [comment]
Sounds good! The default behaviour keeps the same colour, regardless of whether it is being hovered over or not. I'll work on this on the weekend when I have a bit more free time&mdash;I don't expect it to take very long.

<img width="385" alt="screen shot 2017-03-15 at 11 46 29 pm" src="https://cloud.githubusercontent.com/assets/6836385/23980973/aebe5ea4-09d9-11e7-9f9c-275ade0f360d.png">
