### ISSUE TITLE
GPM Update 18th April

### ISSUE THREAD

**Issue by Alipoodle** [gmusic-utils/gmusic-theme.js#70]
![image](https://cloud.githubusercontent.com/assets/17199186/25132738/71530a00-2442-11e7-9e71-093643ab7946.png)
![image](https://cloud.githubusercontent.com/assets/17199186/25132762/81b2612a-2442-11e7-8fa5-20eb13139dec.png)
![image](https://puu.sh/vod7t/bc730178e9.png)

😢 Gonna be a bit of work to do.

**Comment by chrismou** [comment]
At this point I'm pretty sure they're just doing it to mess with us :joy:

**Comment by MarshallOfSound** [comment]
Uhhh, already fixed 😆 

https://github.com/gmusic-utils/gmusic-theme.js/commit/2399e8037858494598e009378ded4d076e6a38df

**Comment by Alipoodle** [comment]
✋ 👋 Boi
That was quick

**Comment by Alipoodle** [comment]
I think this might only apply to the "Paid" version of GPM.
Edit: Didn't see the js.
