### ISSUE TITLE
Text is black on black on default dark theme

### ISSUE THREAD

**Issue by phil-kt** [gmusic-utils/gmusic-theme.js#71]
See image attached:
![screen shot 2017-04-19 at 10 56 13 am](https://cloud.githubusercontent.com/assets/620506/25186697/f36c85dc-24ee-11e7-8b81-0a99819351af.png)

Version 4.2.0 on OSX Sierra 10.12.4

**Comment by jostrander** [comment]
Already fixed in master, checked closed issues.
