### ISSUE TITLE
Light Mode Theming + Misc.

### ISSUE THREAD

**Issue by FlyingGoats** [gmusic-utils/gmusic-theme.js#9]
- Requesting primary color theming in light mode (Eg. Blue primary in attached screenshot).
  ![lightmodetheme](https://cloud.githubusercontent.com/assets/17249361/13104092/c7c88478-d5a6-11e5-8466-0291d0692328.jpg)
- This next one is a bit pedantic but its getting to the designer in me. In dark mode the small dividers in the left content pane appear out of place due to being lighter than the background. I propose they be darker and that the scroll bar be non-transparent:

![dividerproposal](https://cloud.githubusercontent.com/assets/17249361/13104105/e21f48e8-d5a6-11e5-93c0-b88d5af5e764.jpg)

I'm also going to request again for the thin window border to be hidden _when in full screen mode_, once again for consistency with other applications.

Thanks for all the hard work!
Luke

**Comment by chrismou** [comment]
@FlyingGoats What are you referring to when you mention the window border? The border around the entire app?

If so, it's outside the scope of the theming library to control something like that. You'll probably need to request that from whichever app you're using (I'm guessing it's https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-)

**Comment by FlyingGoats** [comment]
@chrismou You are correct on both counts. I might leave it for things to die down before I re-raise it in GPMDP, lots of more important issues there at the moment.

The rest can sit here as an enhancement request until someone benevolent has free time. I lack the necessary skills... I see Radiant Player has more robust theming so I have hope :+1:

**Comment by MarshallOfSound** [comment]
Robust... Lol... More options maybe, but no offense to radiant there themes are very hard to customize / extend.  That's why this library exists :+1: 

I have a WIP for this feature on my local, there is just a couple of bugs to be worked out :+1:

**Comment by chrismou** [comment]
@MarshallOfSound Don't act all jealous, you know Radiant has the best theming. All 3 of them ;-)

**Comment by MarshallOfSound** [comment]
:cactus: :+1: :100: :8ball: :facepunch: :melon: 

Of course, of course.  Have some emojis as an appology :+1:

**Comment by MarshallOfSound** [comment]
@chrismou @FlyingGoats 

I pushed my code into a PR, I think it's stable / ready for implementation

https://github.com/gmusic-utils/gmusic-theme.js/pull/17

**Comment by FlyingGoats** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: !!!

**Comment by MarshallOfSound** [comment]
Implemented in #17

**Comment by MarshallOfSound** [comment]
For people interested I just implemented this theme style in GPMDP

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/commit/b7efd98d9db101a0e460935fbe2b8d7679d20b76

Should be out next release :+1:
